"use client";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
// import FilterButtons from "./filter-buttons";
import ProjectList from "./project-list";
// import { useState } from "react";
import { useQuery } from "@tanstack/react-query";

import "@/styles/globals.css";
import { HomeAPI } from "@xxx/services-api";

export default function Home() {
  // const [selectedCategory, setSelectedCategory] = useState<string>("All");

  const { data: projects } = useQuery({
    queryKey: ["projects"],
    queryFn: HomeAPI.getProjects,
  });

  console.log("projects", projects);
  // const categories = Object.values(projects || []).map((proj) => proj.tag);
  // categories.unshift("All");
  // const allCategories = uniq(categories);

  return (
    <>
      <Head>
        <title>XXX Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <article className="portfolio active" data-page="portfolio">
          <header>
            <h2 className="h2 article-title">XXX</h2>
          </header>

          <ProjectList
            allOptions={(projects || []).map((item) => {
              return {
                value: item.id + "",
                name: item.name,
                // category: item.tag,
              };
            })}
          ></ProjectList>
        </article>
      </main>
    </>
  );
}
