name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
    paths:
      - "packages/home-index/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PREVIEWING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PREVIEWING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: supbase link
        working-directory: packages/home-index
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: supbase db push
        working-directory: packages/home-index
        run: supabase db push
